apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  selector:
    matchLabels:
      app: notification
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: dongja3/notification:0.3
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
          env:
            - name: SERVER_PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    svc: notification
spec:
  selector:
    app: notification
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31080
  type: NodePort